name: Pull Request Validation

on:
  push:
    branches:
      - main

jobs:
  pull-request-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1


      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform select workspace
        id: workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=./env/dev/dev.tfvars

      - name: Terraform Apply
        id: apply
        run: terraform apply -var-file=./env/dev/dev.tfvars

